defaults: &defaults
  adapter: mysql2
  # encoding: unicode
  pool: 5
  username: root
  password:
  # password: realwol
  encoding: utf8

development:
  <<: *defaults
  database: blog_development
test:
  <<: *defaults
  database: blog_test
production:
  <<: *defaults
  database: blog_production
